Add a mkzeros helper
Signed-off-by: Mark Fasheh <mfasheh@suse.de>

diff --git a/tests/common b/tests/common
--- a/tests/common
+++ b/tests/common
@@ -27,3 +27,13 @@ _run_dd()
 	exit 1
     fi
 }
+
+_run_mkzeros()
+{
+    $MKZEROS -q $@
+    _ret=$?
+    if [ $_ret -ne 0 ]; then
+	echo "dd failure: Error code is $_ret"
+	exit 1
+    fi
+}
